import type { GeolocateEventTypes, MapEventTypes } from '../types';

export enum MapboxStatus {
  Disposed = -1,
  NotLoaded,
  Loading,
  Loaded,
  Error,
}

export const MapboxEvents: (keyof MapEventTypes)[] = [
  'error',
  'load',
  'idle',
  'remove',
  'render',
  'resize',
  'webglcontextlost',
  'webglcontextrestored',
  'dataloading',
  'data',
  'tiledataloading',
  'sourcedataloading',
  'sourcedata',
  'styledata',
  'styleimagemissing',
  'dataabort',
  'sourcedataabort',
  'boxzoomcancel',
  'boxzoomstart',
  'boxzoomend',
  'touchcancel',
  'touchmove',
  'touchend',
  'touchstart',
  'click',
  'contextmenu',
  'dblclick',
  'mousemove',
  'mouseup',
  'mousedown',
  'mouseout',
  'mouseover',
  'movestart',
  'move',
  'moveend',
  'zoomstart',
  'zoom',
  'zoomend',
  'rotatestart',
  'rotate',
  'rotateend',
  'dragstart',
  'drag',
  'dragend',
  'pitchstart',
  'pitch',
  'pitchend',
  'wheel',
  'terrain',
];

export const GeolocateEvents: (keyof GeolocateEventTypes)[] = [
  'geolocate',
  'error',
  'outofmaxbounds',
  'trackuserlocationstart',
  'trackuserlocationend',
];
